version: 2

builds:
  - binary: acme-dns-client
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -extldflags '-static'
    goos:
      - linux
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64

archives:
  - id: tgz
    formats: tar.gz

    format_overrides:
        - goos: windows
          formats: zip
